# Generated by Django 4.0.6 on 2022-07-16 02:44

import API.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('property_image', models.ImageField(blank=True, upload_to=API.models.property_directory_path)),
                ('price', models.BigIntegerField()),
                ('dimension', models.IntegerField()),
                ('no_bedrooms', models.IntegerField(blank=True, default=0)),
                ('no_bathrooms', models.IntegerField(blank=True, default=0)),
                ('description', models.CharField(max_length=250)),
                ('details', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('property_type', models.CharField(choices=[('Landed', 'LANDED'), ('House', 'HOUSE')], default='Landed', max_length=10)),
                ('deal_type', models.CharField(choices=[('SALE', 'SALE'), ('RENT', 'RENT'), ('LEASE', 'LEASE')], default='SALE', max_length=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.location')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to=API.models.property_directory_path_for_Images, verbose_name='Image')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.property')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
